/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TeacherTeacherIdRouteImport } from './routes/teacher.$teacherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherIdRoute = TeacherTeacherIdRouteImport.update({
  id: '/teacher/$teacherId',
  path: '/teacher/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRoute
  '/schedule': typeof ScheduleRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRoute
  '/schedule': typeof ScheduleRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRoute
  '/schedule': typeof ScheduleRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/packages' | '/schedule' | '/teacher/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/packages' | '/schedule' | '/teacher/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/packages'
    | '/schedule'
    | '/teacher/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PackagesRoute: typeof PackagesRoute
  ScheduleRoute: typeof ScheduleRoute
  TeacherTeacherIdRoute: typeof TeacherTeacherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$teacherId': {
      id: '/teacher/$teacherId'
      path: '/teacher/$teacherId'
      fullPath: '/teacher/$teacherId'
      preLoaderRoute: typeof TeacherTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PackagesRoute: PackagesRoute,
  ScheduleRoute: ScheduleRoute,
  TeacherTeacherIdRoute: TeacherTeacherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
