/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as TeacherTeacherIdRouteImport } from './routes/teacher.$teacherId'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherIdRoute = TeacherTeacherIdRouteImport.update({
  id: '/teacher/$teacherId',
  path: '/teacher/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRoute
  '/schedule': typeof ScheduleRoute
  '/teach': typeof TeachRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRoute
  '/schedule': typeof ScheduleRoute
  '/teach': typeof TeachRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRoute
  '/schedule': typeof ScheduleRoute
  '/teach': typeof TeachRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/packages'
    | '/schedule'
    | '/teach'
    | '/teacher/$teacherId'
    | '/teacher/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/packages'
    | '/schedule'
    | '/teach'
    | '/teacher/$teacherId'
    | '/teacher/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/packages'
    | '/schedule'
    | '/teach'
    | '/teacher/$teacherId'
    | '/teacher/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PackagesRoute: typeof PackagesRoute
  ScheduleRoute: typeof ScheduleRoute
  TeachRoute: typeof TeachRoute
  TeacherTeacherIdRoute: typeof TeacherTeacherIdRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$teacherId': {
      id: '/teacher/$teacherId'
      path: '/teacher/$teacherId'
      fullPath: '/teacher/$teacherId'
      preLoaderRoute: typeof TeacherTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PackagesRoute: PackagesRoute,
  ScheduleRoute: ScheduleRoute,
  TeachRoute: TeachRoute,
  TeacherTeacherIdRoute: TeacherTeacherIdRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
