/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherTeacherIdRouteImport } from './routes/teacher.$teacherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherIdRoute = TeacherTeacherIdRouteImport.update({
  id: '/teacher/$teacherId',
  path: '/teacher/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teacher/$teacherId': typeof TeacherTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teacher/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teacher/$teacherId'
  id: '__root__' | '/' | '/teacher/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeacherTeacherIdRoute: typeof TeacherTeacherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$teacherId': {
      id: '/teacher/$teacherId'
      path: '/teacher/$teacherId'
      fullPath: '/teacher/$teacherId'
      preLoaderRoute: typeof TeacherTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeacherTeacherIdRoute: TeacherTeacherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
